- name: "Setup {{ ansible_user }} SSH key for server"
  community.crypto.openssh_keypair:
    path: "/home/{{ ansible_user }}/.ssh/{{ ansible_user }}_id_ed25519"
    size: 4096
    type: ed25519
    comment: "{{ ansible_user }}@server.local for {{ device }}"

- name: "Copy {{ ansible_user }} SSH key"
  delegate_to: server.local
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '/home/{{ ansible_user }}/.ssh/{{ ansible_user }}_id_ed25519.pub') }}"
  become: yes

# - name: "Setup server initramfs unlock SSH key"
#   community.crypto.openssh_keypair:
#     path: "/home/{{ ansible_user }}/.ssh/server_id_ed25519"
#     size: 4096
#     type: ed25519
#     comment: "Unlock server.local for {{ device }}"
#   become: yes

# - name: "Copy server initramfs unlock SSH key"
#   delegate_to: server.local
#   ansible.posix.authorized_key:
#     state: present
#     user: root
#     path: /etc/dropbear/initramfs/authorized_keys
#     key: "{{ lookup('file', '/home/{{ ansible_user }}/.ssh/server_id_ed25519.pub') }}"
#   become: yes
