- name: Create btrbk SSH folder
  file:
    path: /etc/btrbk/ssh
    state: directory
  become: yes

- name: Setup btrbk SSH key
  community.crypto.openssh_keypair:
    path: /etc/btrbk/ssh/id_ed25519
    size: 4096
    type: ed25519
    comment: "btrbk@server.local"
  become: yes

- name: Copy btrbk SSH key
  delegate_to: server.local
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/etc/btrbk/ssh/id_ed25519.pub') }}"
  become: yes

- name: Copy config file
  copy:
    src: "{{ playbook_dir }}/roles/btrbk/files/btrbk.conf"
    dest: /etc/btrbk
    mode: '0640'
  become: yes

- name: Create /btrfs_pool
  file:
    path: /btrfs_pool
    state: directory
  become: yes

- name: Mount /btrfs_pool
  ansible.posix.mount:
    path: /btrfs_pool
    src: "UUID={{ ansible_facts['device_links']['uuids']['dm-0'][0] }}"
    fstype: btrfs
    opts: subvolid=5,compress=zstd:1,x-systemd.device-timeout=0
    state: mounted
  become: yes
