- include_tasks: rpmfusion.yml

- include_tasks: vscodium.yml

- name: Install DNF packages
  package:
    name:
      - thunderbird
      - codium
      - yt-dlp
      - gimp
      - lollypop
      - vlc
      - syncthing
      - evolution-data-server
      - wireguard-tools
      - btrbk
      - python3-dnf-plugin-snapper
      - borgbackup
      - lm_sensors
      - gnome-extensions-app
      - gnome-shell-extension-pop-shell
      - setzer
      - texlive-scheme-minimal
      - texlive-outlines
      - texlive-parskip
      - texlive-inter
      - texlive-fontaxes
      - latexmk
      - smartmontools

    state: present
  become: yes

- include_tasks: nim.yml

- include_tasks: flatpak.yml